server:
  port: 8769

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false

    serviceUrl:
#    指定服务地址
      defaultZone: http://peer1:8761/eureka/