server:
  port: 8761

spring.profiles.active: standalone

---
spring.profiles: standalone

eureka:
  environment: ${spring.profiles.active}      # 设置 eureka 使用的环境名
  instance:
    hostname: localhost

  server:
    enable-self-preservation: false

  client:
  # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
  # 配置 eureka 服务地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/